### ISSUE TITLE
Unable to `yarn start` when updating to prealpha 44

### ISSUE THREAD

**Issue by kev-ngo** [polywrap/demos#18]
## Issue
Fail to compile when using `yarn start` after updating to prealpha 44 (see screenshot).

## Steps to repo
1) pull `prealpha.44` branch: [https://github.com/polywrap/demos/tree/prealpha.44](https://github.com/polywrap/demos/tree/prealpha.44)
2) `cd demos/simple-storage/dapp`
3) rm -rf node_modules
4) rm yarn.lock
5) yarn
6) yarn start

## Screenshots
![image](https://user-images.githubusercontent.com/69411313/134097039-ca0a81d0-692b-4d24-98e4-8625c75d7793.png)

**Comment by dOrgJelli** [comment]
Fixed by upgrading typescript version to >= 3.8
