### ISSUE TITLE
Demo: Using the HTTP plugin

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/demos#24]
An example usage would be querying data-providing endpoints, for instance this one: https://etherscan.io/chart/gasprice?output=csv

**Comment by dOrgJelli** [comment]
A thread discussing this: https://discord.com/channels/796821176743362611/888436412121247817/933781448756973658

**Comment by fhrryDeveloper** [comment]
Above discord channel link is not working now

**Comment by alantomjose** [comment]
Hi, Is this still open?

**Comment by rihp** [comment]
@alantomjose  it's assigned but no response yet from dev, so we might reasign to someone else

join our discord.polywrap.io to be in sync with our job board

**Comment by sarath-hotspot** [comment]
Hey, I see this issue is open now. I would like to try this.

**Comment by sarath-hotspot** [comment]
Raised PR for http plugin demo in "integrations" repo. 
https://github.com/polywrap/integrations/pull/19
