### ISSUE TITLE
Demo: plugin(s)

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/demos#33]

**Comment by evanjacobs** [comment]
The link from the docs on the "[Plugin an existing JS SDK](https://docs.polywrap.io/guides/create-js-plugin)" page points to:
https://github.com/polywrap/monorepo/tree/prealpha/packages/js/plugins

Should that page be updated to also include a link to the plugins listed above?

**Comment by dOrgJelli** [comment]
Yes great point, will update @evanjacobs

**Comment by dOrgJelli** [comment]
Going to close this for now, LMK if you think otherwise :)
