### ISSUE TITLE
Demo: TypeScript Plugin

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/demos#37]

**Comment by evanjacobs** [comment]
A couple of comments/observations:
1. The docs reference a `src/manifest.ts` file but I still have `web3api.yaml`. I believe I'm on the latest version of the cli that generated this project.
2. The link under "Example Plugins" goes to github.com/Web3-API. It is redirected correctly to github.com/polywrap but should nevertheless be updated.

**Comment by dOrgJelli** [comment]
Thank you for catching this. I've pushed corrections for this here: https://github.com/polywrap/documentation/pull/158

Would appreciate a review if you have a moment @evanjacobs :pray:

**Comment by dOrgJelli** [comment]
Corrections have been made, going to close this issue for now.
