### ISSUE TITLE
Demo: TypeScript + Node.JS App

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/demos#40]

**Comment by evanjacobs** [comment]
A couple of comments/suggestions:
1. It seems like there should be a link between the documentation and the demo app (and vice versa).
2. Does the warning on the docs page still apply?

> Currently Chrome and Brave are the only supported browsers. This restriction will be removed very shortly.

Otherwise, this looks good to me.

**Comment by dOrgJelli** [comment]
Great catches @evanjacobs, fixed this here: https://github.com/polywrap/documentation/commit/764f739cf92315585aff27133e7178c52353d7f5
