### ISSUE TITLE
Demo: application(s)

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/demos#44]

**Comment by evanjacobs** [comment]
Perhaps we should add a link to the Uniswap app from the [polywrap/demos README](https://github.com/polywrap/demos)?

Actually, I see that there is a link below that to [polywrap/integrations README](https://github.com/polywrap/integrations) which includes a link to the Uniswap v2 (and hopefully soon v3) demo. Do we need to clarify what we mean by apps vs. integrations?

**Comment by dOrgJelli** [comment]
> Do we need to clarify what we mean by apps vs. integrations?

Hmm, I think integrations is a higher-order set, where a sub-set of integrations are apps.

**Comment by evanjacobs** [comment]
> Hmm, I think integrations is a higher-order set, where a sub-set of integrations are apps.

Ok, that makes sense. I think I was getting hung up on using "Demos" to show "simple" wrappers & plugins while "Integrations" is being used for more complex ones. I'm fine with this organization for now and we can always revisit it later.

**Comment by dOrgJelli** [comment]
Amazing :clap: closing :heavy_check_mark:
