### ISSUE TITLE
I want all polywrap demos to be updated to the latest release

### ISSUE THREAD

**Issue by Niraj-Kamdar** [polywrap/demos#54]
- [x] #55
- [x] #56
    - [x] Hello-world wrapper
    - [x] simple-storage wrapper
    - [x] HTTP query demo wrapper
- [x] #63 
- [x] #78

**Comment by Niraj-Kamdar** [comment]
### Demo repo structure after refactor

- demos
  - fetch-metadata
    - app
  - hello-world
    - wrapper
      - assemblyscript
      - rust
    - app
  - simple-storage
    - wrapper
      - assemblyscript
      - rust
    - app
  - subgraph-query
    - wrapper
      - assemblyscript
      - rust
  - http-demo (nice to have)
    - wrapper
      - assemblyscript
      - rust
    - app

**Comment by Niraj-Kamdar** [comment]
@namesty Go ahead! Make sure to assign yourself as the assignee in the issue.

**Comment by Niraj-Kamdar** [comment]
You can task helo-world and simple-storage since HTTP wrapper still needs some rework. @krisbitney was also interested in it so, @krisbitney if you don't mind you can rework HTTP demo wrapper for both AS and Rust

**Comment by krisbitney** [comment]
> You can task helo-world and simple-storage since HTTP wrapper still needs some rework. @krisbitney was also interested in it so, @krisbitney if you don't mind you can rework HTTP demo wrapper for both AS and Rust

Sounds good

**Comment by krisbitney** [comment]
Just to clarify, should I be writing a wrapper that makes some HTTP queries or should i be writing a wrapper for making HTTP queries?

**Comment by Niraj-Kamdar** [comment]
@krisbitney Write the wrapper that makes some HTTP queries, We should show how to make get, post, put, delete, etc REST API calls

**Comment by cbrzn** [comment]
Hey friends I will take care of apps :-D
