### ISSUE TITLE
Add Jest testing for getIpfsData and setIpfsData functions

### ISSUE THREAD

**Issue by kev-ngo** [polywrap/demos#6]
## Issue
- A simple recipe testing such as `w3 query` on the `e2e.json` is not scalable.  Jest testing will allow us to have faster and more efficient testing going forward.

**Comment by MrKevinOConnell** [comment]
I'll do this 👍🏻

**Comment by pragmatismer666** [comment]
Hi, sir,
I am professional developer with rich experience.
Will provide best quality result for you.

0x9ade9076A47518627012626FDAfebbF5eeE1bB0f

**Comment by Niraj-Kamdar** [comment]
@kev-ngo Is this issue still relevant?

**Comment by kev-ngo** [comment]
I don't think so

**Comment by Niraj-Kamdar** [comment]
Closing this since unrelevant after origin
